<?php
const APPID = 'wxb6c74c1f97c5a72e';
const SECRET = '0a35f4a623dfe98f7bdd8d9d1098a084';
const MCH_ID = '1511838561';
const MCH_KEY = '34r4eju78io986543ju8765r87uvbnx6';
const UNIFIED_API =  'https://api.mch.weixin.qq.com/pay/unifiedorder';
const SESSION_API = 'https://api.weixin.qq.com/sns/jscode2session';
const KEY = '1234567890';
variable_set('notify_url', 'https://0376866.com/wait_notify');
include 'utility/utility.inc';
include 'common/common.inc';
function weixinpay_menu(){
  $items = array();
  $items['checkout/pay'] = array(
    'title' => 'Checkout',
    'page callback' => 'weixinpay_checkout_pay_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixinpay.pay.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'

  );
  $items['wait_notify'] = array(
    'title' => 'Waitting Weipay result notify',
    'page callback' => 'weixinpay_wait_notify_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixinpay.notify.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'

  );
  $items['userinit'] = array(
    'title' => 'Wei User Init',
    'page callback' => 'weixin_user_init_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.login.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['setuserinfo'] = array(
    'title' => 'Wei xin user update',
    'page callback' => 'weixin_set_user_info',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.login.inc',
    'file path' => drupal_get_path('module', 'weixinpay'). '/include'
  );
  $items['updatenozzle'] = array(
    'title' => 'Update Nozzle',
    'page callback' => 'weixin_update_nozzle_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.updates.inc',
    'file path' => drupal_get_path('module', 'weixinpay'). '/include'
  );
  $items['getrecords'] = array(
    'title' => 'Pay Records',
    'page callback' => 'weixin_payrecords_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.payrecord.inc',
    'file path' => drupal_get_path('module', 'weixinpay'). '/include'
  );

  $items['detect'] = array(
    'title' => 'Detect',
    'page callback' => 'weixin_detect_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.detect.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['setaff'] = array(
    'title' => 'Set Affiliation',
    'page callback' => 'weixin_setaff_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.login.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['getprice'] = array(
    'title' => 'Get Price',
    'page callback' => 'weixin_getprice_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.info.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['createinvoice'] = array(
    'title' => 'Create Invoice',
    'page callback' => 'weixin_create_invoice',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.settings.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['deleteinvoice'] = array(
    'title' => 'Create Invoice',
    'page callback' => 'weixin_delete_invoice',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.settings.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['initinvoicelist'] = array(
    'title' => 'Init Invoice List',
    'page callback' => 'weixin_initinvoicelist_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.settings.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['confirminvoice'] = array(
    'title' => 'Confirm Invoice',
    'page callback' => 'weixin_confirm_invoice_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.settings.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['test'] = array(
    'title' => 'Testing',
    'page callback' => 'test_callback',
    'access callback' => TRUE,

  );
  return $items;
}

function test_callback(){
  $node = node_load(379);
  dpm($node);
  return 'hello';
}
function weixinpay_node_update($node){
  weixinpay_node_detect($node);
  weixin_rules_update($node);
  weixinpay_wxuser_mark($node);
}
function weixin_rules_update($node){
  $usable_rule_set_types = array('pay_out_rule_a_collection', 'pay_out_rule_b_collection');
  if(in_array($node->type, $usable_rule_set_types) ){
    $node_wrapper = entity_metadata_wrapper('node', $node);
    if($node_wrapper->field_enable->value() == 1){
      $enable_rule_sets = get_all_enable_rule_sets($usable_rule_set_types);
      foreach ($enable_rule_sets as $nid => $e_node) {
        if($nid != $node->nid){
          $e_node_wrapper = entity_metadata_wrapper('node', $e_node);
          $e_node_wrapper->field_enable->set(0);
          $e_node_wrapper->save();
        }
      }
    }
  }
}
function weixinpay_node_delete($node){
  weixinpay_node_detect($node);
  weixinpay_wxuser_mark($node);
}
function weixinpay_node_insert($node){
    weixinpay_node_detect($node);
    if($node->type == 'wx_user' && $node->status == 1){
      variable_set('ch_wxuser', time());
    }
}

function weixinpay_node_detect($node){
  if($node->type == 'nozzle' && $node->status == 1){
    variable_set('ch_nozzle', time());
    return;
  }
  if($node->type == 'pay_record' && $node->status == 1){
    variable_set('ch_record', time());
    return;
  }

}
function weixinpay_taxonomy_term_update($term){
  weixinpay_term_detect($term);
}
function weixinpay_taxonomy_term_delete($term){
  weixinpay_term_detect($term);
}
function weixinpay_taxonomy_term_insert($term){
  weixinpay_term_detect($term);
}
function weixinpay_term_detect($term){
  if($term->vocabulary_machine_name == 'oil_type'){
    variable_set('ch_price', time());
  }
}

function weixinpay_wxuser_mark($node){
  if($node->type == 'wx_user'){
    $changes = variable_get('wexuser_changed', array());
    $changes[] = $node->nid;
    variable_set('wexuser_changed', $changes);
  }
}

function weixinpay_menu_alter(&$items){
   foreach($items as $path => &$item){
     if($item['module'] == 'weixinpay'){
       $callback = $item['page callback'];
       $arguments = isset($item['page arguments'])? $item['page arguments']: array();
       array_unshift($arguments, $callback);
       $item['page arguments'] = $arguments;
       $item['page callback'] = 'weixin_request_callback_wrapper';
     }
   }
}
