<?php
const APPID = 'wxb6c74c1f97c5a72e';
const SECRET = '0a35f4a623dfe98f7bdd8d9d1098a084';
const MCH_ID = '1511838561';
const MCH_KEY = '34r4eju78io986543ju8765r87uvbnx6';
const UNIFIED_API =  'https://api.mch.weixin.qq.com/pay/unifiedorder';
const SESSION_API = 'https://api.weixin.qq.com/sns/jscode2session';
const KEY = '12345678';
variable_set('notify_url', 'https://0376866.com/wait_notify');
include 'utility/utility.inc';
include 'common/common.inc';
function weixinpay_menu(){
  $items = array();
  $items['checkout/pay'] = array(
    'title' => 'Checkout',
    'page callback' => 'weixinpay_checkout_pay_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixinpay.pay.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'

  );
  $items['wait_notify'] = array(
    'title' => 'Waitting Weipay result notify',
    'page callback' => 'weixinpay_wait_notify_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixinpay.notify.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'

  );
  $items['wxlogin'] = array(
    'title' => 'Wei xin Login',
    'page callback' => 'weixin_login_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.login.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'

  );
  $items['wxuserupdate'] = array(
    'title' => 'Wei xin user update',
    'page callback' => 'weixin_user_update_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.login.inc',
    'file path' => drupal_get_path('module', 'weixinpay'). '/include'
  );
  $items['updatenozzle'] = array(
    'title' => 'Update Nozzle',
    'page callback' => 'weixin_update_nozzle_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.updates.inc',
    'file path' => drupal_get_path('module', 'weixinpay'). '/include'
  );
  $items['getrecords'] = array(
    'title' => 'Pay Records',
    'page callback' => 'weixin_payrecords_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.payrecord.inc',
    'file path' => drupal_get_path('module', 'weixinpay'). '/include'
  );

  $items['detect'] = array(
    'title' => 'Detect',
    'page callback' => 'weixin_detect_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.detect.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['setaff'] = array(
    'title' => 'Set Affiliation',
    'page callback' => 'weixin_setaff_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.login.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['getprice'] = array(
    'title' => 'Get Price',
    'page callback' => 'weixin_getprice_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'weixin.info.inc',
    'file path' => drupal_get_path('module', 'weixinpay') . '/include'
  );
  $items['test'] = array(
    'title' => 'Testing',
    'page callback' => 'test_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}

function test_callback(){
 dpm(urldecode('%E5%8F%82%E6%95%B0%E9%95%BF%E5%BA%A6%E6%9C%89%E8%AF%AF'));
 return 'hello';

}
function weixinpay_node_update($node){
  watchdog('node update', $node->title);
  weixinpay_node_detect($node);
  $usable_rule_sets = array('pay_out_rule_a_collection', 'pay_out_rule_b_collection');
  $node_wrapper = entity_metadata_wrapper('node', $node);
  if(in_array($node->type, $usable_rule_sets) && $node_wrapper->field_enable->value() == 1){
    $enable_rule_sets = get_all_enable_rule_sets($usable_rule_sets);
    foreach ($enable_rule_sets as $nid => $e_node) {
      if($nid != $node->nid){
        $e_node_wrapper = entity_metadata_wrapper('node', $e_node);
        $e_node_wrapper->field_enable->set(0);
        $e_node_wrapper->save();

      }
    }
  }
}
function weixinpay_node_delete($node){
  watchdog('node delete', $node->title);
  weixinpay_node_detect($node);
}
function weixinpay_node_insert($node){
  watchdog('node insert', $node->title);
    weixinpay_node_detect($node);
}
function weixinpay_node_detect($node){
  if($node->type == 'nozzle'){
    variable_set('ch_nozzle', time());
  }
  if($node->type == 'pay_record'){
    variable_set('ch_record', time());
  }
}
function weixinpay_taxonomy_term_update($term){
  weixinpay_term_detect($term);
}
function weixinpay_taxonomy_term_delete($term){
  weixinpay_term_detect($term);
}
function weixinpay_taxonomy_term_insert($term){
  weixinpay_term_detect($term);
}
function weixinpay_term_detect($term){
  if($term->vocabulary_machine_name == 'oil_type'){
    variable_set('ch_price', time());
  }
}
